-- ==========================================================================
-- ConnectHub: full schema bootstrap for a fresh neondb
-- Concatenation of Auth + Message + Room + Notification InitialPostgres.
-- Each section creates its own __EFMigrationsHistory_<service> table so
-- multiple DbContexts can share a single database without colliding.
-- Paste this in Neon's SQL editor (https://console.neon.tech).
-- ==========================================================================

-- ─── Auth ──────────────────────────────────────────────────────────
﻿CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Auth" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Auth" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" character varying(50) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "PasswordHash" text NOT NULL,
    "AvatarUrl" text,
    "Bio" character varying(300),
    "IsOnline" boolean NOT NULL,
    "LastSeen" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "GoogleId" text,
    "GitHubId" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_UserName" ON "Users" ("UserName");

INSERT INTO "__EFMigrationsHistory_Auth" ("MigrationId", "ProductVersion")
VALUES ('20260501085652_InitialPostgres', '8.0.10');

COMMIT;


-- ─── Message ──────────────────────────────────────────────────────────
﻿CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Message" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Message" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Messages" (
    "MessageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer,
    "RoomId" integer,
    "Content" character varying(2000) NOT NULL,
    "MessageType" integer NOT NULL,
    "IsRead" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "IsEdited" boolean NOT NULL,
    "IsDelivered" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "DeliveredAt" timestamp with time zone,
    "ReadAt" timestamp with time zone,
    "EditedAt" timestamp with time zone,
    "MediaUrl" text,
    "ReplyToMessageId" integer,
    "DeletedForUserIds" character varying(500),
    CONSTRAINT "PK_Messages" PRIMARY KEY ("MessageId")
);

CREATE INDEX "IX_Messages_Direct" ON "Messages" ("SenderId", "ReceiverId");

CREATE INDEX "IX_Messages_Room" ON "Messages" ("RoomId", "SentAt");

INSERT INTO "__EFMigrationsHistory_Message" ("MigrationId", "ProductVersion")
VALUES ('20260501085737_InitialPostgres', '8.0.10');

COMMIT;


-- ─── Room ──────────────────────────────────────────────────────────
﻿CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Room" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Room" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ChatRooms" (
    "RoomId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoomName" character varying(100) NOT NULL,
    "Description" character varying(500),
    "RoomType" integer NOT NULL,
    "AvatarUrl" text,
    "CreatedBy" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "MaxMembers" integer NOT NULL,
    CONSTRAINT "PK_ChatRooms" PRIMARY KEY ("RoomId")
);

CREATE TABLE "RoomMembers" (
    "MemberId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoomId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Role" integer NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_RoomMembers" PRIMARY KEY ("MemberId"),
    CONSTRAINT "FK_RoomMembers_ChatRooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "ChatRooms" ("RoomId") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatRooms_RoomName" ON "ChatRooms" ("RoomName");

CREATE UNIQUE INDEX "IX_RoomMembers_RoomId_UserId" ON "RoomMembers" ("RoomId", "UserId");

INSERT INTO "__EFMigrationsHistory_Room" ("MigrationId", "ProductVersion")
VALUES ('20260501085842_InitialPostgres', '8.0.10');

COMMIT;


-- ─── Notification ──────────────────────────────────────────────────────────
﻿CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Notification" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Notification" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Notifications" (
    "NotificationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RecipientId" integer NOT NULL,
    "SenderId" integer,
    "Type" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Message" character varying(1000) NOT NULL,
    "RelatedId" integer,
    "IsRead" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId")
);

CREATE INDEX "IX_Notifications_RecipientId" ON "Notifications" ("RecipientId");

CREATE INDEX "IX_Notifications_RecipientId_IsRead" ON "Notifications" ("RecipientId", "IsRead");

INSERT INTO "__EFMigrationsHistory_Notification" ("MigrationId", "ProductVersion")
VALUES ('20260501085938_InitialPostgres', '8.0.10');

COMMIT;


