CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Auth" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Auth" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" character varying(50) NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "PasswordHash" text NOT NULL,
    "AvatarUrl" text,
    "Bio" character varying(300),
    "IsOnline" boolean NOT NULL,
    "LastSeen" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "GoogleId" text,
    "GitHubId" text,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_UserName" ON "Users" ("UserName");

INSERT INTO "__EFMigrationsHistory_Auth" ("MigrationId", "ProductVersion")
VALUES ('20260501085652_InitialPostgres', '8.0.10');

COMMIT;

