CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Message" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Message" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Messages" (
    "MessageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer,
    "RoomId" integer,
    "Content" character varying(2000) NOT NULL,
    "MessageType" integer NOT NULL,
    "IsRead" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "IsEdited" boolean NOT NULL,
    "IsDelivered" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "DeliveredAt" timestamp with time zone,
    "ReadAt" timestamp with time zone,
    "EditedAt" timestamp with time zone,
    "MediaUrl" text,
    "ReplyToMessageId" integer,
    "DeletedForUserIds" character varying(500),
    CONSTRAINT "PK_Messages" PRIMARY KEY ("MessageId")
);

CREATE INDEX "IX_Messages_Direct" ON "Messages" ("SenderId", "ReceiverId");

CREATE INDEX "IX_Messages_Room" ON "Messages" ("RoomId", "SentAt");

INSERT INTO "__EFMigrationsHistory_Message" ("MigrationId", "ProductVersion")
VALUES ('20260501085737_InitialPostgres', '8.0.10');

COMMIT;

