CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Notification" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Notification" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Notifications" (
    "NotificationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RecipientId" integer NOT NULL,
    "SenderId" integer,
    "Type" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Message" character varying(1000) NOT NULL,
    "RelatedId" integer,
    "IsRead" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId")
);

CREATE INDEX "IX_Notifications_RecipientId" ON "Notifications" ("RecipientId");

CREATE INDEX "IX_Notifications_RecipientId_IsRead" ON "Notifications" ("RecipientId", "IsRead");

INSERT INTO "__EFMigrationsHistory_Notification" ("MigrationId", "ProductVersion")
VALUES ('20260501085938_InitialPostgres', '8.0.10');

COMMIT;

