CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Room" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Room" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ChatRooms" (
    "RoomId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoomName" character varying(100) NOT NULL,
    "Description" character varying(500),
    "RoomType" integer NOT NULL,
    "AvatarUrl" text,
    "CreatedBy" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "MaxMembers" integer NOT NULL,
    CONSTRAINT "PK_ChatRooms" PRIMARY KEY ("RoomId")
);

CREATE TABLE "RoomMembers" (
    "MemberId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoomId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Role" integer NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_RoomMembers" PRIMARY KEY ("MemberId"),
    CONSTRAINT "FK_RoomMembers_ChatRooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "ChatRooms" ("RoomId") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatRooms_RoomName" ON "ChatRooms" ("RoomName");

CREATE UNIQUE INDEX "IX_RoomMembers_RoomId_UserId" ON "RoomMembers" ("RoomId", "UserId");

INSERT INTO "__EFMigrationsHistory_Room" ("MigrationId", "ProductVersion")
VALUES ('20260501085842_InitialPostgres', '8.0.10');

COMMIT;

