# Project identification
sonar.projectKey=ConnectHub_Frontend
sonar.projectName=ConnectHub Frontend
sonar.projectVersion=1.0

# Source configuration
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.language=ts

# Server configuration
sonar.host.url=http://localhost:9000
sonar.login=squ_2fe8ddb5f52323d450b8a0a3b6639971e5c685b2

# Exclusions (to keep LOC low and focus on your code)
sonar.exclusions=**/node_modules/**,**/*.spec.ts,dist/**,src/assets/**

# Type Script / Javascript specific
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/connect-hub-web/lcov.info
